spring:
  application:
    name: demo
  profiles:
    active: dev
server:
  port: 80
---

spring:
  profiles: dev
  datasource:
    # mysql≈‰÷√
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    # redis ≈‰÷√
    redis:
      url: 127.0.0.1
      port: 6379
      password:
# mybatis plus≈‰÷√
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.inphase.imccp.demo.entity
